FROM node:0.12.15

# Add source code
ADD TutorMeetS-Socket.IO /app
WORKDIR /app

# Install dependancies
RUN apt-get update
RUN apt-get install -y vim
RUN npm i -g pm2 
RUN npm i --unsafe-perm

# Build source
RUN npm run build

# Start service 
CMD npm start
