# kurento-media-server
#

FROM      ubuntu:14.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y wget curl vim

RUN echo "deb http://ubuntu.kurento.org trusty-dev kms6" | tee /etc/apt/sources.list.d/kurento-dev.list \
    && wget -O - http://ubuntu.kurento.org/kurento.gpg.key | apt-key add - \
    && apt-get update \
    && apt-get -y install kurento-media-server-6.0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./entrypoint-kms.sh /entrypoint.sh
CMD /entrypoint.sh
