# kurento-media-server
#

FROM      ubuntu:14.04

EXPOSE 8888
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y wget curl vim

RUN echo "deb http://ubuntu.kurento.org trusty kms6" | tee /etc/apt/sources.list.d/kurento.list \
    && wget -O - http://ubuntu.kurento.org/kurento.gpg.key | apt-key add - \
    && apt-get update \
    && apt-get -y install kurento-media-server-6.0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY kms/certificate.pem /certificate.pem
COPY kms/libkmselementsplugins.so /usr/lib/x86_64-linux-gnu/gstreamer-1.5/
COPY ./entrypoint-kms.sh /entrypoint.sh
CMD /entrypoint.sh
