version: '2'
services:
  kms:
    image: "${registry}research/kms"
#    environment:
#      - EXTERNAL_IP=
#      - MIN_PORT=49152
#      - MAX_PORT=65535
    network_mode: host
    volumes:
      - /mnt/s3/record:/mnt/s3/record
      - /mnt/nfs/record:/mnt/nfs/record
  turn:
    image: "${registry}research/turn"
    network_mode: host
#    environment:
#      - EXTERNAL_IP=LOCAL_IP
#      - LOCAL_IP=
#      - USERNAME=kurento
#      - PASSWORD=kurento
#      - MIN_PORT=49152
#      - MAX_PORT=65535
    restart: on-failure:10
  manarola:
    image: "${registry}research/manarola"
    ports:
     - "3000:3000"
    links: 
     - redis
  redis:
    image: redis
    volumes:
      - /redis_data:/data
#    ports:
#      - "6379:6379"
  wowza:
    image: "${registry}research/wowza"
    network_mode: host
    volumes:
      - /sdpfiles:/sdpfiles

  nginx:
    image: "${registry}research/nginx"
    ports:
     - "443:443"
     - "3000:3000"
    environment:
     - CAGLIARI_IP=172.31.24.162
     - CAGLIARI_PORT=443
     - MANAROLA_IP=172.31.24.162
     - MANAROLA_PORT=3000
#     - NGINX_STATUS_ALLOW_IP=metrics.dev.tutormeet.plus
     - NGINX_STATUS_ALLOW_IP=52.196.246.136
  app:
    image: "${registry}research/cagliari"
#    environment:
#      - PORT=443
    links:
     - kms
     - turn
     - manarola
    ports:
     - "443:443"
    volumes:
      - /mnt/s3/record:/mnt/s3/record
      - /mnt/nfs/record:/mnt/nfs/record
      - /sdpfiles:/sdpfiles
