version: '2'
services:
  kms:
    image: "${registry}/kms"
    environment:
#      - EXTERNAL_IP=
       - TURN_USERNAME=tutormeetplus
       - TURN_PASSWORD=f73e38a6-d3a3-4d32-b5dc-d95e38d066ba
#      - MIN_PORT=49152
#      - MAX_PORT=65535
    network_mode: host
    volumes:
      - /mnt/s3/record:/mnt/s3/record
      - /mnt/nfs/record:/mnt/nfs/record
  kms-dev:
    image: "${registry}/kms-dev"
    environment:
#      - EXTERNAL_IP=
       - TURN_USERNAME=tutormeetplus
       - TURN_PASSWORD=f73e38a6-d3a3-4d32-b5dc-d95e38d066ba
#      - MIN_PORT=49152
#      - MAX_PORT=65535
    network_mode: host
    volumes:
      - /mnt/s3/record:/mnt/s3/record
      - /mnt/nfs/record:/mnt/nfs/record
  turn:
    image: "${registry}/turn"
    network_mode: host
    environment:
#      - EXTERNAL_IP=LOCAL_IP
#      - LOCAL_IP=
      - USERNAME=tutormeetplus
      - PASSWORD=f73e38a6-d3a3-4d32-b5dc-d95e38d066ba
#      - MIN_PORT=49152
#      - MAX_PORT=65535
    restart: on-failure:10
  manarola:
    image: "${registry}/manarola"
    ports:
     - "3000:3000"
    links: 
     - redis
  redis:
    image: redis
    volumes:
      - /redis_data:/data
    ports:
      - "6379:6379"
  wowza:
    image: "${registry}/wowza"
    network_mode: host
    volumes:
      - /sdpfiles:/sdpfiles

  nginx:
    image: "${registry}/nginx"
    ports:
     - "443:443"
     - "3000:3000"
     - "3030:3030"
    environment:
     - CAGLIARI_IP=172.31.17.187
     - CAGLIARI_PORT=8080
     - MANAROLA_IP=172.31.24.162
     - MANAROLA_PORT=3000
     - MATERIAL_IP=172.16.7.180
     - MATERIAL_PORT=3030
     - MATERIAL_MAX_BODY_SIZE=30M
#     - NGINX_STATUS_ALLOW_IP=metrics.dev.tutormeet.plus
     - NGINX_STATUS_ALLOW_IP=52.196.246.136
  app:
    image: "${registry}/cagliari:develop"
#    environment:
#      - PORT=443
    links:
     - kms
     - turn
     - manarola
    ports:
     - "443:443"
    volumes:
      - /mnt/s3/record:/mnt/s3/record
      - /mnt/nfs/record:/mnt/nfs/record
      - /sdpfiles:/sdpfiles
