#!/bin/bash

NGINX_CONF_FILE=/etc/nginx/nginx.conf

sed -i -- "s/WWW_HOST/$WWW_HOST/g" ${NGINX_CONF_FILE}
sed -i -- "s/WWW_PORT/$WWW_PORT/g" ${NGINX_CONF_FILE}
sed -i -- "s/CAGLIARI_HOST/$CAGLIARI_HOST/g" ${NGINX_CONF_FILE}
sed -i -- "s/CAGLIARI_PORT/$CAGLIARI_PORT/g" ${NGINX_CONF_FILE}
sed -i -- "s/MANAROLA_HOST/$MANAROLA_HOST/g" ${NGINX_CONF_FILE}
sed -i -- "s/MANAROLA_PORT/$MANAROLA_PORT/g" ${NGINX_CONF_FILE}
sed -i -- "s/MATERIAL_HOST/$MATERIAL_HOST/g" ${NGINX_CONF_FILE}
sed -i -- "s/MATERIAL_PORT/$MATERIAL_PORT/g" ${NGINX_CONF_FILE}
material_max_body_size=${MATERIAL_MAX_BODY_SIZE:=30M}
sed -i -- "s/MATERIAL_MAX_BODY_SIZE/$material_max_body_size/g" ${NGINX_CONF_FILE}
sed -i -- "s/NGINX_STATUS_ALLOW_IP/$NGINX_STATUS_ALLOW_IP/g" ${NGINX_CONF_FILE}

echo WWW_HOST=$WWW_HOST
echo WWW_PORT=$WWW_PORT
echo CAGLIARI_HOST=$CAGLIARI_HOST
echo CAGLIARI_PORT=$CAGLIARI_PORT
echo MANAROLA_HOST=$MANAROLA_HOST
echo MANAROLA_PORT=$MANAROLA_PORT
echo MATERIAL_HOST=$MATERIAL_HOST
echo MATERIAL_PORT=$MATERIAL_PORT
echo MATERIAL_MAX_BODY_SIZE=$MATERIAL_MAX_BODY_SIZE
echo NGINX_STATUS_ALLOW_IP=$NGINX_STATUS_ALLOW_IP

exec nginx -g 'daemon off;'
