#!/bin/bash

NGINX_CONF_FILE=/etc/nginx/nginx.conf

sed -i -- "s/CAGLIARI_IP/$CAGLIARI_IP/g" ${NGINX_CONF_FILE}
sed -i -- "s/CAGLIARI_PORT/$CAGLIARI_PORT/g" ${NGINX_CONF_FILE}
sed -i -- "s/MANAROLA_IP/$MANAROLA_IP/g" ${NGINX_CONF_FILE}
sed -i -- "s/MANAROLA_PORT/$MANAROLA_PORT/g" ${NGINX_CONF_FILE}
sed -i -- "s/NGINX_STATUS_ALLOW_IP/$NGINX_STATUS_ALLOW_IP/g" ${NGINX_CONF_FILE}

echo CAGLIARI_IP=$CAGLIARI_IP
echo CAGLIARI_PORT=$CAGLIARI_PORT
echo MANAROLA_IP=$MANAROLA_IP
echo MANAROLA_PORT=$MANAROLA_PORT
echo NGINX_STATUS_ALLOW_IP=$NGINX_STATUS_ALLOW_IP

exec nginx -g 'daemon off;'
