#!/bin/bash

NGINX_CONF_FILE=/etc/nginx/nginx.conf

sed -i -- "s/CAGLIARI_IP/$CAGLIARI_IP/g" ${NGINX_CONF_FILE}
sed -i -- "s/CAGLIARI_PORT/$CAGLIARI_PORT/g" ${NGINX_CONF_FILE}
sed -i -- "s/MANAROLA_IP/$MANAROLA_IP/g" ${NGINX_CONF_FILE}
sed -i -- "s/MANAROLA_PORT/$MANAROLA_PORT/g" ${NGINX_CONF_FILE}
sed -i -- "s/MATERIAL_IP/$MATERIAL_IP/g" ${NGINX_CONF_FILE}
sed -i -- "s/MATERIAL_PORT/$MATERIAL_PORT/g" ${NGINX_CONF_FILE}
material_max_body_size=${MATERIAL_MAX_BODY_SIZE:=30M}
sed -i -- "s/MATERIAL_MAX_BODY_SIZE/$material_max_body_size/g" ${NGINX_CONF_FILE}
sed -i -- "s/NGINX_STATUS_ALLOW_IP/$NGINX_STATUS_ALLOW_IP/g" ${NGINX_CONF_FILE}

echo CAGLIARI_IP=$CAGLIARI_IP
echo CAGLIARI_PORT=$CAGLIARI_PORT
echo MANAROLA_IP=$MANAROLA_IP
echo MANAROLA_PORT=$MANAROLA_PORT
echo MATERIAL_IP=$MATERIAL_IP
echo MATERIAL_PORT=$MATERIAL_PORT
echo MATERIAL_MAX_BODY_SIZE=$MATERIAL_MAX_BODY_SIZE
echo NGINX_STATUS_ALLOW_IP=$NGINX_STATUS_ALLOW_IP

exec nginx -g 'daemon off;'
