app:
  ports:
    - 8080:8080
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=AWS-TW-01
  image: 123923422374.dkr.ecr.us-east-1.amazonaws.com/research/cagliari:develop
  links:
    - redis
  volumes:
    - /mnt/s3/record:/mnt/s3/record
turn:
  image: 123923422374.dkr.ecr.us-east-1.amazonaws.com/research/turn
  net: host
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=AWS-TW-01
kms:
  image: 123923422374.dkr.ecr.us-east-1.amazonaws.com/research/kms
  volumes:
    - /mnt/s3/record:/mnt/s3/record
    - /sdpfiles:/sdpfiles
  net: host
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=AWS-TW-01
manarola:
  ports:
  - 3000:3000
  - 9100:9100
  - 9116:9116
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=AWS-TW-01
  image: 123923422374.dkr.ecr.us-east-1.amazonaws.com/research/manarola:develop
  links:
    - redis
redis:
  image: redis
  volumes:
    - /redis_data:/data
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=AWS-TW-01
