app:
  ports:
    - 443:443
  image: ${DOCKER_REPO}/cagliari:develop
  links:
    - redis
  volumes:
    - /mnt/s3/record:/mnt/s3/record
    - /mnt/nfs/record:/mnt/nfs/record
    - /sdpfiles:/sdpfiles
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${RANCHER_HOSTNAME}
turn:
  image: ${DOCKER_REPO}/turn
  environment:
    - USERNAME=tutormeetplus
    - PASSWORD=f73e38a6-d3a3-4d32-b5dc-d95e38d066ba
  net: host
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${RANCHER_HOSTNAME}
kms:
  image: ${DOCKER_REPO}/kms
  environment:
    - TURN_USERNAME=tutormeetplus
    - TURN_PASSWORD=f73e38a6-d3a3-4d32-b5dc-d95e38d066ba
  volumes:
    - /mnt/s3/record:/mnt/s3/record
    - /mnt/nfs/record:/mnt/nfs/record
    - /sdpfiles:/sdpfiles
  net: host
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${RANCHER_HOSTNAME}
manarola:
  ports:
  - 3000:3000
  - 9116:9116
  image: ${DOCKER_REPO}/manarola:develop
  links:
    - redis
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${RANCHER_HOSTNAME}
# wowza:
#   image: "${DOCKER_REPO}/wowza"
#   net: host
#   volumes:
#     - /sdpfiles:/sdpfiles
#   labels:
#     io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${RANCHER_HOSTNAME}
redis:
  image: redis
  volumes:
    - /redis_data:/data
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${RANCHER_HOSTNAME}
