app:
  ports:
    - 8080:8080
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${rancher_host}
  image: 123923422374.dkr.ecr.us-east-1.amazonaws.com/research/cagliari
  links:
    - redis
  volumes:
    - /record:/record
turn:
  image: 123923422374.dkr.ecr.us-east-1.amazonaws.com/research/turn
  net: host
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${rancher_host}
kms:
  image: 123923422374.dkr.ecr.us-east-1.amazonaws.com/research/kms
  volumes:
    - /record:/record
  net: host
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${rancher_host}
manarola:
  ports:
  - 3000:3000
  - 9100:9100
  - 9116:9116
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${rancher_host}
  image: 123923422374.dkr.ecr.us-east-1.amazonaws.com/research/manarola
  links:
    - redis
redis:
  image: redis
  volumes:
    - /redis_data:/data
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${rancher_host}