app:
  ports:
    - 8080:8080
  image: ${DOCKER_REPO}/cagliari:develop
  links:
    - redis
  volumes:
    - /mnt/s3/record:/mnt/s3/record
    - /mnt/nfs/record:/mnt/nfs/record
    - /sdpfiles:/sdpfiles
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${RANCHER_HOSTNAME}
turn:
  image: ${DOCKER_REPO}/turn
  net: host
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${RANCHER_HOSTNAME}
kms:
  image: ${DOCKER_REPO}/kms
  volumes:
    - /mnt/s3/record:/mnt/s3/record
    - /mnt/nfs/record:/mnt/nfs/record
    - /sdpfiles:/sdpfiles
  net: host
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${RANCHER_HOSTNAME}
manarola:
  ports:
  - 3000:3000
  - 9116:9116
  image: ${DOCKER_REPO}/manarola:develop
  links:
    - redis
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${RANCHER_HOSTNAME}
# wowza:
#   image: "${DOCKER_REPO}/wowza"
#   network_mode: host
#   volumes:
#     - /sdpfiles:/sdpfiles
redis:
  image: redis
  volumes:
    - /redis_data:/data
  labels:
    io.rancher.scheduler.affinity:host_label: io.rancher.host.hostname=${RANCHER_HOSTNAME}