app:
  image: ${DOCKER_REPO}/cagliari:develop
  links:
    - redis-master:redis
  volumes:
    - /mnt/s3/record:/mnt/s3/record
    - /mnt/nfs/record:/mnt/nfs/record
    - /sdpfiles:/sdpfiles
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: app.enabled=true
turn:
  image: ${DOCKER_REPO}/turn
  environment:
    - USERNAME=tutormeetplus
    - PASSWORD=f73e38a6-d3a3-4d32-b5dc-d95e38d066ba
  net: host
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: true
    io.rancher.scheduler.affinity:host_label: turn.enabled=true
kms:
  image: ${DOCKER_REPO}/kms
  environment:
    - TURN_USERNAME=tutormeetplus
    - TURN_PASSWORD=f73e38a6-d3a3-4d32-b5dc-d95e38d066ba
  volumes:
    - /mnt/s3/record:/mnt/s3/record
    - /mnt/nfs/record:/mnt/nfs/record
    - /sdpfiles:/sdpfiles
  net: host
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: true
    io.rancher.scheduler.affinity:host_label: kms.enabled=true
manarola:
  ports:
  - 9116:9116
  image: ${DOCKER_REPO}/manarola:develop
  links:
    - redis-master:redis
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft: io.rancher.stack_service.name=$${stack_name}/app

nginx:
  image: "${DOCKER_REPO}/nginx"
  ports:
   - "443:443"
   - "3000:3000"
   - "3030:3030"
  environment:
   - CAGLIARI_IP=app
   - CAGLIARI_PORT=443
   - MANAROLA_IP=manarola
   - MANAROLA_PORT=3000
#     - NGINX_STATUS_ALLOW_IP=metrics.dev.tutormeet.plus
   - NGINX_STATUS_ALLOW_IP=52.196.246.136
   - MATERIAL_IP=ec2-52-196-139-6.ap-northeast-1.compute.amazonaws.com
   - MATERIAL_PORT=3030
  volumes:
   - certs:/etc/ssl/localcerts
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: true
    io.rancher.scheduler.affinity:host_label: proxy.enabled=true
redis-master:
  image: redis
  ports: 
    - 6379:6379
  volumes:
    - /redis_data:/data
# redis-slave:
#   image: redis
#   command: redis-server --slaveof redis-master 6379
#   links:
#     - redis-master
#   labels:
#     io.rancher.scheduler.global: true
# redis-sentinel:
#   image: erichsu/redis-sentinel
#   environment:
#     - SENTINEL_DOWN_AFTER=5000
#     - SENTINEL_FAILOVER=5000    
#   links:
#     - redis-master
#     - redis-slave
#   labels:
#     io.rancher.scheduler.global: true
# wowza:
#   image: "${DOCKER_REPO}/wowza"
#   net: host
#   volumes:
#     - /sdpfiles:/sdpfiles
#  labels:
#    io.rancher.container.pull_image: always
